spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/wordly
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
