spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wordly}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:yourpassword}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
